export const STORES: string[] = [
  "Clothing Junction - Aero Centre",
  "Clothing Junction - Alex Mall",
  "Clothing Junction - Alexandra Plaza",
  "Clothing Junction - Balfour Park",
  "Clothing Junction - Bara Mall",
  "Clothing Junction - Westwood Mall",
  "Clothing Junction - Matlosana Mall",
  "Clothing Junction - Scottsville Mall",
  "Clothing Junction - The Glen",
  "Clothing Junction - Midlands Mall",
  "Clothing Junction - Kim Park Centre",
  "Clothing Junction - Krugersdorp Market St",
  "Clothing Junction - Kingsburgh Centre",
  "Clothing Junction - Newcastle Sanlam Centre",
  "Clothing Junction - Greytown Pine Street",
  "Clothing Junction - Verulam Wick Street",
  "Clothing Junction - Ladysmith San Marco Centre",
  "Clothing Junction - Mabopane Square",
  "Clothing Junction - Northmead Mall",
  "Clothing Junction - Dawn Park Shopping Centre",
  "Clothing Junction - Wonderboom Junction",
  "Clothing Junction - Carnival Mall",
  "Clothing Junction - Bedworth Park",
  "Clothing Junction - Newtown Junction Mall",
  "Clothing Junction - Yarona Centre",
  "Clothing Junction - Boksburg Commissioner St",
  "Clothing Junction - Bloed Street Mall",
  "Clothing Junction - Pretoria Bosman St",
  "Clothing Junction - Eldorado Park",
  "Clothing Junction - Brits Murray Ave",
  "Clothing Junction - Festival Mall",
  "Clothing Junction - Mall of the South",
  "Clothing Junction - Parkdene Boulevard"
];
